const characters = [
    {
        nama:"Barbara",
        img:"Barbara.jpg",
        description:"",
        sound:"",
        element:"hydro"
    },
    {
        nama:"Chongyun",
        img:"Chongyun.jpg",
        description:"",
        sound:"",
        element:"cyro"
    },
    {
        nama:"Hu Tao",
        img:"Hu-Tao.png",
        description:"",
        sound:"",
        element:"pyro"
    },
    {
        nama:"Kamisato Ayato",
        img:"Kamisato-Ayato.png",
        description:"",
        sound:"",
        element:"hydro"
    },
    {
        nama:"Kazuha",
        img:"Kazuha.jpg",
        description:"",
        sound:"",
        element:"anemo"
    },
    {
        nama:"Keqing",
        img:"Keqing.jpg",
        description:"",
        sound:"",
        element:"electro"
    },
    {
        nama:"Layla",
        img:"Layla.png",
        description:"",
        sound:"",
        element:"cyro"
    },
    {
        nama:"Raiden Shogun",
        img:"Raiden-Shogun.png",
        description:"",
        sound:"",
        element:"electro"
    },
    {
        nama:"Shenhe",
        img:"Shenhe.jpg",
        description:"",
        sound:"",
        element:"cyro"
    },
    {
        nama:"Sucrose",
        img:"Sucrose.jpg",
        description:"",
        sound:"",
        element:"anemo"
    },
    {
        nama:"Tighnari",
        img:"Tighnari.png",
        description:"",
        sound:"",
        element:"dendro"
    },
    {
        nama:"Xiao",
        img:"Xiao.png",
        description:"",
        sound:"",
        element:"anemo"
    },
    {
        nama:"Yae Miko",
        img:"Yae-Miko.jpg",
        description:"",
        sound:"",
        element:"electro"
    },
    {
        nama:"Zhongli",
        img:"Zhongli.png",
        description:"",
        sound:"",
        element:"geo"
    },
    {
        nama:"Albedo",
        img:"Albedo.png",
        description:"",
        sound:"",
        element:"geo"
    },
    {
        nama:"Arataki Itto",
        img:"Arataki-itto.png",
        description:"",
        sound:"",
        element:"geo"
    },
    {
        nama:"Dainsleif",
        img:"Dainsleif.jpg",
        description:"",
        sound:"",
        element:"cyro"
    },
    {
        nama:"Mona",
        img:"Mona.jpg",
        description:"",
        sound:"",
        element:"hydro"
    },
    {
        nama:"Ganyu",
        img:"Ganyu.png",
        description:"",
        sound:"",
        element:"cyro"
    },
    {
        nama:"Faruzan",
        img:"Faruzan.png",
        description:"",
        sound:"",
        element:"anemo"
    },
    {
        nama:"Diluc",
        img:"Diluc.jpg",
        description:"",
        sound:"",
        element:"pyro"
    },
    {
        nama:"Yoimiya",
        img:"Yoimiya.png",
        description:"",
        sound:"",
        element:"pyro"
    },
    {
        nama:"Beidou",
        img:"Beidou.png",
        description:"",
        sound:"",
        element:"electro"
    },
    {
        nama:"Kujou Sara",
        img:"Kujou-Sara.jpg",
        description:"",
        sound:"",
        element:"electro"
    },
    {
        nama:"Venti",
        img:"Venti.jpg",
        description:"",
        sound:"",
        element:"anemo"
    },
    {
        nama:"Yelan",
        img:"Yelan.jpg",
        description:"",
        sound:"",
        element:"hydro"
    },
    {
        nama:"Zhongli",
        img:"Zhongli.png",
        description:"",
        sound:"",
        element:"geo"
    },
];